name: vbank

services:
  redis:
    image: redis/redis-stack:6.2.6-v19
    container_name: redis
    environment:
      REDIS_ARGS: "--requirepass cantremember"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
